// ============================================================
// Nzigestan — App-wide constants & seed data
// ============================================================
import type { CastMember, MerchProduct, Event } from "@/types";

export const PAYBILL = "522522";
export const ACCOUNT_LIVE = "NZIGE-LIVE";
export const ACCOUNT_MERCH = "ORDER-NZG";
export const ACCOUNT_EVENTS = "EVENTS-NZG";
export const YOUTUBE_CHANNEL = "https://www.youtube.com/@thekisianganipodcast/";

export const VERNACULAR = [
  { phrase: "Tuko kwa barabara", meaning: "We are on the journey" },
  { phrase: "Itawesa sana", meaning: "It will definitely work" },
  { phrase: "You guy", meaning: "Nairobi conversational emphasis" },
  { phrase: "Kuingia mtaro", meaning: "Going wildly off-script" },
  { phrase: "Cheki", meaning: "Look / listen here" },
  { phrase: "Hii ni Laf Lyf", meaning: "The comedy collective sign-off" },
];

export const TICKER_TERMS = [
  "#TukoKwaBarabara",
  "#ItawesaSana",
  "#YouGuy",
  "#KuingiaMtaro",
  "#Cheki",
  "#HiiNiLafLyf",
  "#RepublicOfNzigestan",
  "#LafLyfLive",
  "#NairobiUnderground",
];

export const CAST: CastMember[] = [
  {
    id: "emmanuel",
    name: "Emmanuel Kisiangani",
    role: "Host · Philosopher · Creator",
    micChannel: 1,
    gainDb: 58,
    image: "/assets/cast/emmanuel-kisiangani.png",
  },
  {
    id: "bashir",
    name: "Bashir Halaiki",
    alias: "Bash",
    role: "Co-Host · Stand-Up Powerhouse",
    micChannel: 2,
    gainDb: 54,
    image: "/assets/cast/bashir-halaiki.png",
  },
  {
    id: "nduta",
    name: "Nduta Kariuki",
    alias: "The Queen of Chaos",
    role: "Producer · Cultural Commentator",
    micChannel: 3,
    gainDb: 52,
    image: "/assets/cast/nduta-kariuki.png",
  },
  {
    id: "chinese",
    name: "George Waweru",
    alias: "Chinese",
    role: "Street-Smart Strategist · Urban Analyst",
    micChannel: 4,
    gainDb: 55,
    image: "/assets/cast/george-waweru.png",
  },
  {
    id: "jack",
    name: "Jack Alita",
    role: "Stand-Up Comic · Comedy Writer",
    micChannel: 5,
    gainDb: 56,
    image: "/assets/cast/jack-alita.png",
  },
  {
    id: "mike1",
    name: "Mike 1",
    role: "Laf Lyf Anchor · Studio Technician",
    micChannel: 6,
    gainDb: 50,
    image: "/assets/cast/emmanuel-kisiangani.png", // placeholder until Mike1 asset added
  },
];

export const MERCH_PRODUCTS: MerchProduct[] = [
  {
    id: "nzige-hoodie-black",
    name: "'NZIGE' Drop-Shoulder Hoodie — Black",
    tagline: "450 GSM heavyweight fleece — the official swarm uniform",
    priceKes: 4500,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stockTotal: 100,
    stockRemaining: 18,
    image: "/assets/merch/hoodie-black-male.jpeg",
    gallery: [
      "/assets/merch/hoodie-black-male.jpeg",
      "/assets/merch/hoodies-collection.png",
    ],
  },
  {
    id: "nzige-hoodie-burgundy",
    name: "'NZIGE' Drop-Shoulder Hoodie — Burgundy",
    tagline: "450 GSM heavyweight fleece — locust insignia, deep wine colorway",
    priceKes: 4500,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stockTotal: 80,
    stockRemaining: 32,
    image: "/assets/merch/hoodie-burgundy-female.jpeg",
    gallery: [
      "/assets/merch/hoodie-burgundy-female.jpeg",
      "/assets/merch/hoodie-burgundy-male.jpeg",
      "/assets/merch/hoodies-collection.png",
    ],
  },
  {
    id: "nzige-hoodie-grey",
    name: "'NZIGE' Drop-Shoulder Hoodie — Heather Grey",
    tagline: "450 GSM heavyweight fleece — subtle swarm crest, everyday fit",
    priceKes: 4500,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stockTotal: 80,
    stockRemaining: 45,
    image: "/assets/merch/hoodie-grey-male.jpeg",
    gallery: [
      "/assets/merch/hoodie-grey-male.jpeg",
      "/assets/merch/hoodie-charcoal-male.jpeg",
      "/assets/merch/hoodies-collection.png",
    ],
  },
  {
    id: "nzige-hoodie-jungle-green",
    name: "'NZIGE' Drop-Shoulder Hoodie — Jungle Green",
    tagline: "450 GSM heavyweight fleece — military-grade swarm colorway",
    priceKes: 4500,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stockTotal: 80,
    stockRemaining: 56,
    image: "/assets/merch/hoodie-jungle-green-male.jpeg",
    gallery: [
      "/assets/merch/hoodie-jungle-green-male.jpeg",
      "/assets/merch/hoodie-forest-green-female.jpeg",
      "/assets/merch/hoodies-collection.png",
    ],
  },
  {
    id: "kisiangani-tee",
    name: "Kisiangani Podcast Locust Tee — White",
    tagline: "Premium 240 GSM cotton — two nzige, two mics, one republic",
    priceKes: 2800,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stockTotal: 150,
    stockRemaining: 64,
    image: "/assets/merch/tshirt-white.png",
    gallery: [
      "/assets/merch/tshirt-white.png",
      "/assets/merch/tshirt-man-model.png",
      "/assets/merch/tshirt-lady-model.png",
    ],
  },
  {
    id: "kisiangani-tee-green",
    name: "Kisiangani Podcast Tee — Forest Green",
    tagline: "Pigment-dyed 240 GSM — the crest on deep green",
    priceKes: 2800,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stockTotal: 100,
    stockRemaining: 72,
    image: "/assets/merch/tshirt-green.png",
  },
  {
    id: "nzigestan-sweatshirt",
    name: "Nzigestan Crewneck Sweatshirt — White",
    tagline: "380 GSM brushed fleece — clean crest, cozy everywhere",
    priceKes: 3800,
    category: "streetwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stockTotal: 60,
    stockRemaining: 38,
    image: "/assets/merch/sweatshirt-white.png",
  },
  {
    id: "nzige-cap-black",
    name: "Nzigestan Snapback Cap — Black",
    tagline: "Embroidered locust insignia — dark ops edition",
    priceKes: 1800,
    category: "accessories",
    stockTotal: 80,
    stockRemaining: 41,
    image: "/assets/merch/cap-black.jpeg",
    gallery: [
      "/assets/merch/cap-black.jpeg",
      "/assets/merch/cap-black-male.jpeg",
    ],
  },
  {
    id: "nzige-cap-white",
    name: "Nzigestan Dad Hat — White",
    tagline: "Embroidered locust crest — clean republic edition",
    priceKes: 1800,
    category: "accessories",
    stockTotal: 80,
    stockRemaining: 53,
    image: "/assets/merch/cap-white.jpeg",
    gallery: [
      "/assets/merch/cap-white.jpeg",
      "/assets/merch/cap-white-nzige.jpeg",
    ],
  },
  {
    id: "nzige-tote-bag",
    name: "Nzigestan Canvas Tote Bag — Black",
    tagline: "Heavy-duty 12oz canvas — carry the republic everywhere",
    priceKes: 1500,
    category: "accessories",
    stockTotal: 100,
    stockRemaining: 67,
    image: "/assets/merch/tote-bag-black.jpeg",
  },
  {
    id: "enamel-pins",
    name: "Studio Crew Enamel Pin Set",
    tagline: "4 custom pins on collector card — swarm insignia",
    priceKes: 950,
    category: "accessories",
    stockTotal: 200,
    stockRemaining: 112,
    image: "/assets/branding/locust-emblem-transparent.png",
  },
  {
    id: "thermal-flask",
    name: "'Fuel for the Swarm' Matatu Thermal Flask 500ml",
    tagline: "Matte black laser-engraved — hydration on the odyssey",
    priceKes: 2200,
    category: "essentials",
    stockTotal: 80,
    stockRemaining: 9,
    image: "/assets/branding/brand-asset-2.png",
  },
  {
    id: "notebook",
    name: "Karura Deep Reflections Notebook",
    tagline: "A5 debossed foil cover — document the discourse",
    priceKes: 650,
    category: "essentials",
    stockTotal: 150,
    stockRemaining: 73,
    image: "/assets/branding/brand-asset-3.png",
  },
  {
    id: "coasters",
    name: "Stone & Walnut Coaster Set",
    tagline: "Set of two — for the late-night studio sessions",
    priceKes: 1200,
    category: "essentials",
    stockTotal: 60,
    stockRemaining: 34,
    image: "/assets/branding/brand-asset-4.png",
  },
  {
    id: "sticker-pack",
    name: "Fan Sticker Pack",
    tagline: '"CHEKI" · "You Guy" · "Kuingia Mtaro" · "Itawesa Sana"',
    priceKes: 400,
    category: "stickers",
    stockTotal: 500,
    stockRemaining: 287,
    image: "/assets/branding/wordmark-color-transparent.png",
  },
];

export const EVENTS: Event[] = [
  {
    id: "ngong-hills-ridge-trek",
    category: "swarm-nature-hike",
    title: "Swarm Ridge Expedition",
    subtitle: "Ngong Hills 7 Knuckles Ridge Trek",
    venue: "Ngong Hills, Kajiado County",
    venueCoords: { lat: -1.3667, lng: 36.6333 },
    date: "2026-10-18",
    time: "06:00 EAT",
    capacityTotal: 100,
    capacityBooked: 82,
    coverImage: "/assets/studio/homepage-hero.png",
    ticketTiers: [
      { id: "regular", name: "Regular Citizen Pass", description: "Includes transport from Kencom, guided hike, & bonfire debrief", priceKes: 2500 },
      { id: "vip", name: "Swarm VIP", description: "Front group + branded Matatu Flask + priority boarding", priceKes: 4000 },
      { id: "backstage", name: "Community Backstage Hangout", description: "Post-hike drinks & private podcast recording session with the crew", priceKes: 7500 },
    ],
    status: "on-sale",
  },
  {
    id: "karura-philosophy-walk",
    category: "swarm-nature-hike",
    title: "Karura Forest Philosophy Walk",
    subtitle: "Tuko kwa Barabara Hike #02",
    venue: "Karura Forest, Nairobi",
    venueCoords: { lat: -1.2307, lng: 36.8308 },
    date: "2026-11-08",
    time: "07:30 EAT",
    capacityTotal: 80,
    capacityBooked: 31,
    coverImage: "/assets/studio/homepage-hero.png",
    ticketTiers: [
      { id: "regular", name: "Regular Citizen Pass", description: "Guided forest walk & post-hike podcast debrief", priceKes: 1800 },
      { id: "vip", name: "Swarm VIP", description: "All above + branded flask + crew group photo", priceKes: 3200 },
    ],
    status: "on-sale",
  },
  {
    id: "braeburn-studio-a-sessions",
    category: "studio-live-taping",
    title: "Studio A Sessions — Live Taping",
    subtitle: "Exclusive 45-seat intimate live recording at Braeburn",
    venue: "Braeburn Theatre, Nairobi",
    date: "2026-10-31",
    time: "19:30 EAT",
    capacityTotal: 45,
    capacityBooked: 45,
    coverImage: "/assets/studio/studio-pod.png",
    ticketTiers: [
      { id: "regular", name: "Citizen Pass", description: "Live Q&A & behind-the-scenes mic checks", priceKes: 3500 },
      { id: "vip", name: "VIP Front Row", description: "Front row + post-show drinks with the crew", priceKes: 6000 },
    ],
    status: "sold-out",
  },
  {
    id: "kuingia-mtaro-live",
    category: "comedy-showcase",
    title: '"Kuingia Mtaro Live"',
    subtitle: "Laf Lyf Comedy Showcase — Full House Standup Special",
    venue: "Braeburn Theatre, Nairobi",
    date: "2026-12-06",
    time: "20:00 EAT",
    capacityTotal: 300,
    capacityBooked: 187,
    coverImage: "/assets/studio/studio-pod.png",
    ticketTiers: [
      { id: "regular", name: "Regular Citizen Pass", description: "General admission", priceKes: 2000 },
      { id: "vip", name: "VIP Front Row", description: "Front row + meet & greet", priceKes: 4500 },
      { id: "backstage", name: "Backstage Hangout", description: "Backstage access + all-night crew banter", priceKes: 8000 },
    ],
    status: "on-sale",
  },
];

export const SHIPPING_OPTIONS = [
  { id: "standard", label: "Standard Nairobi Metro Courier (2–3 days)", priceKes: 300 },
  { id: "express", label: "Express Same-Day Studio Runner", priceKes: 500 },
  { id: "pickup", label: "Braeburn Studio Pick-Up (self-collect)", priceKes: 0 },
  { id: "diaspora", label: "International DHL Diaspora Dispatch", priceKes: -1 }, // -1 = calculated separately
];

export const PROMO_CODES: Record<string, { type: "percent" | "gift"; value: number | string }> = {
  ITAWESASANA:  { type: "percent", value: 10 },
  KUINGIAMTARO: { type: "gift",    value: "sticker-pack" },
};

export const NAIROBI_WARDS = [
  "Kilimani", "Westlands", "Nairobi CBD", "Adams Arcade",
  "Lang'ata", "Karen", "Gigiri", "Runda", "South C", "South B",
  "Kasarani", "Roysambu", "Githurai", "Ruiru", "Thika",
  "Eldoret Hub", "Mombasa", "Kisumu", "Other",
];

export const FALLBACK_SEED_EPISODES = [
  {
    id: "7tkGUXetubY",
    youtubeId: "7tkGUXetubY",
    title: "AMAN on a Mission - Kitengela Only",
    thumbnail: "https://i.ytimg.com/vi/7tkGUXetubY/maxresdefault.jpg",
    duration: "2:35:14",
    viewCount: 28400,
    publishedAt: "2026-09-21T15:12:28Z",
    frequency: "blissful-banter" as const,
    tags: ["#TukoKwaBarabara", "#KitengelaOnly", "#ItawesaSana"],
  },
  {
    id: "-dsFDS1jJtM",
    youtubeId: "-dsFDS1jJtM",
    title: "The Kisiangani Podcast ft. Chinese & Bash — Live in Nairobi",
    thumbnail: "https://i.ytimg.com/vi/-dsFDS1jJtM/maxresdefault.jpg",
    duration: "3:02:18",
    viewCount: 45200,
    publishedAt: "2026-09-20T16:40:27Z",
    frequency: "comic-diaries" as const,
    tags: ["#KuingiaMtaro", "#LafLyfLive"],
  },
  {
    id: "H89igvdTVmw",
    youtubeId: "H89igvdTVmw",
    title: "Ty & The Boyz In Kitengela",
    thumbnail: "https://i.ytimg.com/vi/H89igvdTVmw/maxresdefault.jpg",
    duration: "2:14:38",
    viewCount: 39800,
    publishedAt: "2026-09-20T11:01:02Z",
    frequency: "blissful-banter" as const,
    tags: ["#YouGuy", "#TukoKwaBarabara"],
  },
  {
    id: "P8KIV-Y5zWk",
    youtubeId: "P8KIV-Y5zWk",
    title: "Unplugged With Jacob Aliet",
    thumbnail: "https://i.ytimg.com/vi/P8KIV-Y5zWk/maxresdefault.jpg",
    duration: "2:44:50",
    viewCount: 52100,
    publishedAt: "2026-09-18T13:42:59Z",
    frequency: "deep-dives" as const,
    tags: ["#DeepDives", "#Philosophy"],
  },
  {
    id: "kmH60yhIG80",
    youtubeId: "kmH60yhIG80",
    title: "The 12-Hour Jamhuri Day Live Marathon",
    thumbnail: "https://i.ytimg.com/vi/kmH60yhIG80/maxresdefault.jpg",
    duration: "11:58:30",
    viewCount: 98000,
    publishedAt: "2026-09-12T08:00:00Z",
    frequency: "republic-archives" as const,
    tags: ["#12HourLive", "#RepublicArchives"],
  },
];
